# Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices,
along with a collection of mathematical functions to operate on these data structures. In this lesson, we will
cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np

## create an aray using numpy
## create a 1D array

arr1 =np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
## How to reshape array
## 1 D array 
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 Columns

array([[1, 2, 3, 4, 5]])

In [4]:
print(arr2.shape)  ## original size having 5 elements 
arr2 = arr2.reshape(1,5)
print(arr2.shape)  ## Now array is consisting of 1 row and 5 columns
print(arr2)  

(5,)
(1, 5)
[[1 2 3 4 5]]


In [5]:
## 2d Array
arr2 = np.array([[1,3,5,7,9],[2,4,6,8,10]]) ## 1st column [1,3,5,7,9] and 2nd column [2,4,6,8,10]
print(arr2)
print(arr2.shape)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
(2, 5)


In [6]:
## np.arange(start,end,step)

print(np.arange(0,10,2))
print(np.arange(0,10,2).reshape(5,1))

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [7]:
## ones(shape"()") function ## matrix with only ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## eye(n no. of rows and columns) ## identity matrix
np.ones(3)

array([1., 1., 1.])

In [11]:
## Attributes of NUmpy Array

arr = np.array([[1,2,3],[4,5,6]])

print("Array\n", arr) 
print("Shape:" , arr.shape) ##Output : (2,3)
print("Number of Dimensions:", arr.ndim) ## Output: 2
print("Size(number of elements):", arr.size)  ## output: 6
print("Data type:", arr.dtype)  ## Output: int64 (may vary by platform)
print("Iten Size (in bytes):" , arr.itemsize) ## Output: 8 (may vary by platform)

Array
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size(number of elements): 6
Data type: int64
Iten Size (in bytes): 8


## Numpy vectorized operations 

In [13]:
## Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition:",arr1+arr2)

## Element wise substraction
print("Substraction:",arr1-arr2)

## Element wise multiplication
print("Multiplication:",arr1*arr2)

## Element wise division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [14]:
## Universal Functions

arr = np.array([2,3,4,5,6])

## square root sqrt()
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine 
print(np.sin(arr))

## natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## Array Slicing and Indexing

In [15]:
arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(arr[0][0])

1


In [21]:
print(arr[1:]) ## for 2nd and 3rd row 

## For 2nd and 3rd row but from 3rd and 4th column only

print(arr[1:,2:])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[]


In [22]:
print(arr[0:2 , 2: ])

[[3 4]
 [7 8]]


In [23]:
'''
For Array : 
 [[ 1  2  3  4]
 [ 5  #6  #7  8]
 [ 9 #10 #11 12]] 
'''
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [24]:
# Modification Of Array

arr[0,0]= 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [25]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


# Statistical Concepts

In [ ]:
## Statistical concepts  for Normalization

data =np.array([1,2,3,4,5])

# Calculating the central tendency (mean ,median)
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the Data
normalized_data =(data-mean) / std_dev
print("Normalized Data:", normalized_data)  ## gives the output wrt to normal distribution

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [27]:
sample_array = np.array([1,2,3,4,5,6,7,8,9,10])

## mean
mean = np.mean(sample_array)
print("Mean:",mean)

## Median
median = np.median(sample_array)
print("Median:",median)

## Standard Deviation
std_dev = np.std(sample_array)
print("Standard deviation:",std_dev)

## variance
variance =np.var(sample_array)
print("Variance:",variance)


Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [32]:
## logical operations

data=np.array([1,2,3,4,5,6,7,8,9,10])

print((data>5) & (data<=8)) ## Applys condition on data and yields True or False
print(data[(data>5) & (data<=8)])

[False False False False False  True  True  True False False]
[6 7 8]
